
import React, { useState, useRef, useCallback, useEffect } from 'react';
import Cropper, { Area } from 'react-easy-crop';
import { Product, TryOnResult, TryOnRequest } from '../types';
import { geminiService } from '../services/geminiService';
import { getCroppedImg } from '../utils/cropImage';
import { supabase } from '../services/supabaseClient';
import Button from './Button';
import TryOnProcessing from './TryOnProcessing';

interface TryOnModalProps {
  product: Product;
  onClose: () => void;
}

const TryOnModal: React.FC<TryOnModalProps> = ({ product, onClose }) => {
  const [user, setUser] = useState<any>(null);
  const [image, setImage] = useState<string | null>(null);
  const [tempImage, setTempImage] = useState<string | null>(null);
  const [isCropping, setIsCropping] = useState(false);
  const [crop, setCrop] = useState({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(1);
  const [croppedAreaPixels, setCroppedAreaPixels] = useState<Area | null>(null);

  const [height, setHeight] = useState('175');
  const [weight, setWeight] = useState('70');
  const [saveBodyModel, setSaveBodyModel] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isInitialLoading, setIsInitialLoading] = useState(true);
  const [result, setResult] = useState<TryOnResult | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const hasAutoGenerated = useRef(false);

  // Helper to convert URL to Base64
  const urlToBase64 = async (url: string): Promise<string> => {
    try {
      const proxyUrl = `https://corsproxy.io/?${encodeURIComponent(url)}`;
      const response = await fetch(proxyUrl);
      if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
      const blob = await response.blob();
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch (e) {
      console.warn("Proxy fetch failed, attempting direct fetch", e);
      try {
        const response = await fetch(url);
        const blob = await response.blob();
        return new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result as string);
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        });
      } catch (fallbackError) {
        return url;
      }
    }
  };

  // Load User Data & Profile
  useEffect(() => {
    const checkUserAndAutoGenerate = async () => {
      try {
        const { data: { session } } = await supabase.auth.getSession();
        if (session?.user) {
          setUser(session.user);
          const { data: profile } = await supabase
            .from('profiles')
            .select('*')
            .eq('id', session.user.id)
            .single();
          
          if (profile) {
            const h = profile.height || '175';
            const w = profile.weight || '70';
            const img = profile.body_model_url;

            setHeight(h);
            setWeight(w);
            if (img) {
              setImage(img);
              if (!hasAutoGenerated.current) {
                hasAutoGenerated.current = true;
                handleGenerateDirectly(img, h, w);
              }
            }
          }
        }
      } catch (err) {
        console.error("Profile load failed", err);
      } finally {
        setIsInitialLoading(false);
      }
    };
    checkUserAndAutoGenerate();
  }, [product.id]);

  const handleGenerateDirectly = async (img: string, h: string, w: string) => {
    setIsProcessing(true);
    setResult(null);

    try {
      const garmentBase64 = await urlToBase64(product.imageUrl);

      const requestData: TryOnRequest = {
        user_image: img,
        garment_image: garmentBase64,
        category: product.category === 'External' ? 'upper_body' : product.category.toLowerCase().replace(/\s+/g, '_'),
        adjustment_params: {
          height: parseInt(h, 10) || 175,
          weight: parseInt(w, 10) || 70,
          preserve_identity: true
        }
      };

      const res = await geminiService.performTryOn(requestData);
      setResult(res);
    } catch (error) {
      setResult({
        status: 'error',
        imageUrl: '',
        message: "An error occurred while preparing your look."
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleConnectKey = async () => {
    if (window.aistudio?.openSelectKey) {
      await window.aistudio.openSelectKey();
      // Proceed immediately as per race condition rules
      handleGenerate();
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setTempImage(reader.result as string);
        setIsCropping(true);
      };
      reader.readAsDataURL(file);
    }
  };

  const onCropComplete = useCallback((_: Area, croppedAreaPixels: Area) => {
    setCroppedAreaPixels(croppedAreaPixels);
  }, []);

  const handleConfirmCrop = async () => {
    try {
      if (tempImage && croppedAreaPixels) {
        const croppedImage = await getCroppedImg(tempImage, croppedAreaPixels);
        setImage(croppedImage);
        setIsCropping(false);
        setTempImage(null);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handleGenerate = async () => {
    if (!image) return;
    handleGenerateDirectly(image, height, weight);
    
    if (user && saveBodyModel) {
      try {
        await supabase.from('profiles').upsert({
          id: user.id,
          height,
          weight,
          body_model_url: image,
          updated_at: new Date().toISOString()
        });
      } catch (err) {
        console.warn("Failed to update profile", err);
      }
    }
  };

  const handleDownload = () => {
    if (!result?.imageUrl) return;
    const link = document.createElement('a');
    link.href = result.imageUrl;
    link.download = `visionfit-${product.title.toLowerCase().replace(/\s+/g, '-')}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    if (!result?.imageUrl) return;
    try {
      if (navigator.share) {
        if (result.imageUrl.startsWith('data:')) {
          const res = await fetch(result.imageUrl);
          const blob = await res.blob();
          const file = new File([blob], 'visionfit-tryon.png', { type: 'image/png' });
          if (navigator.canShare && navigator.canShare({ files: [file] })) {
            await navigator.share({
              files: [file],
              title: 'My VisionFit AI Look',
              text: `Check out this ${product.title} I just tried on with VisionFit AI!`,
            });
            return;
          }
        }
        await navigator.share({
          title: 'VisionFit AI Try-On',
          text: `I just tried on the ${product.title} with VisionFit AI!`,
          url: window.location.href
        });
      } else {
        await navigator.clipboard.writeText(window.location.href);
        alert('Link copied to clipboard!');
      }
    } catch (error: any) {
      if (error.name !== 'AbortError' && error.message !== 'Share canceled') {
        console.error('Error sharing:', error);
      }
    }
  };

  const resetTryOn = () => {
    setResult(null);
    setIsProcessing(false);
    if (!user) setImage(null);
    hasAutoGenerated.current = true;
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center px-4 py-6">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose}></div>
      
      <div className="relative bg-white w-full max-w-4xl rounded-3xl shadow-2xl overflow-hidden flex flex-col md:flex-row max-h-[90vh]">
        <div className="hidden md:flex md:w-1/3 bg-zinc-50 border-r border-zinc-100 flex-col overflow-y-auto">
          <img src={product.imageUrl} alt={product.title} className="w-full aspect-[3/4] object-cover" />
          <div className="p-6 space-y-2">
            <span className="text-xs font-bold uppercase tracking-wider text-zinc-400">{product.category}</span>
            <h2 className="text-xl font-bold">{product.title}</h2>
            <p className="text-sm text-zinc-500">{product.description}</p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 md:p-10 flex flex-col relative">
          <button 
            onClick={onClose}
            className="absolute top-6 right-6 p-2 hover:bg-zinc-100 rounded-full transition-colors z-50 bg-white/80"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
          </button>

          {isInitialLoading ? (
            <div className="flex-1 flex flex-col items-center justify-center space-y-4">
              <div className="w-10 h-10 border-4 border-zinc-100 border-t-black rounded-full animate-spin"></div>
              <p className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Loading Profile...</p>
            </div>
          ) : isCropping && tempImage ? (
            <div className="flex-1 flex flex-col">
              <div className="space-y-2 mb-6">
                <h2 className="text-2xl font-bold">Crop your photo</h2>
                <p className="text-zinc-500 text-sm">Align the garment to your body frame for the best AI visualization.</p>
              </div>
              <div className="relative flex-1 bg-zinc-900 rounded-2xl overflow-hidden min-h-[300px]">
                <Cropper
                  image={tempImage}
                  crop={crop}
                  zoom={zoom}
                  aspect={3 / 4}
                  onCropChange={setCrop}
                  onCropComplete={onCropComplete}
                  onZoomChange={setZoom}
                />
              </div>
              <div className="py-6 space-y-4">
                <div className="flex gap-3">
                  <Button variant="secondary" className="flex-1" onClick={() => { setIsCropping(false); setTempImage(null); }}>Cancel</Button>
                  <Button className="flex-1" onClick={handleConfirmCrop}>Confirm</Button>
                </div>
              </div>
            </div>
          ) : isProcessing ? (
            <div className="flex-1 flex items-center justify-center">
                <TryOnProcessing userImage={image} />
            </div>
          ) : result?.message === 'QUOTA_EXHAUSTED' ? (
            <div className="flex-1 flex flex-col items-center justify-center space-y-8 text-center px-4">
              <div className="w-24 h-24 bg-amber-50 text-amber-500 rounded-full flex items-center justify-center">
                <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
              </div>
              <div className="space-y-3">
                <h3 className="text-2xl font-black text-black">Daily Limit Reached</h3>
                <p className="text-zinc-500 text-sm max-w-sm mx-auto">
                  The shared VisionFit AI quota has been exceeded for today. To continue generating unlimited looks, connect your own paid API key.
                </p>
                <a 
                  href="https://ai.google.dev/gemini-api/docs/billing" 
                  target="_blank" 
                  className="text-[10px] font-black uppercase tracking-widest text-black underline underline-offset-4 hover:text-zinc-600 block pt-2"
                >
                  Learn about Gemini API Billing
                </a>
              </div>
              <div className="flex flex-col gap-3 w-full max-w-xs">
                <Button className="w-full py-5" onClick={handleConnectKey}>Connect Personal API Key</Button>
                <Button variant="ghost" onClick={resetTryOn}>Back to Fitting Room</Button>
              </div>
            </div>
          ) : result?.status === 'error' ? (
            <div className="flex-1 flex flex-col items-center justify-center space-y-6 text-center">
              <div className="w-20 h-20 bg-red-50 text-red-500 rounded-full flex items-center justify-center">
                <svg className="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Something went wrong</h3>
                <p className="text-zinc-500 text-sm max-w-sm">{result.message}</p>
              </div>
              <Button variant="secondary" onClick={resetTryOn}>Try Again</Button>
            </div>
          ) : result?.status === 'success' ? (
            <div className="space-y-6 flex-1 flex flex-col items-center">
              <div className="text-center space-y-2">
                <h2 className="text-2xl font-bold">Look Rendered</h2>
                <p className="text-zinc-500 text-sm">Identity-preserved and physically accurate.</p>
              </div>
              
              <div className="relative group w-full max-w-sm aspect-[3/4] rounded-2xl overflow-hidden shadow-2xl border border-zinc-100 bg-zinc-100">
                <img src={result.imageUrl} alt="Result" className="w-full h-full object-cover" />
                
                <div className="absolute top-4 left-4">
                    <div className="bg-white/90 backdrop-blur px-3 py-1.5 rounded-full flex items-center gap-2 shadow-sm border border-white/20">
                        <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                        <span className="text-[10px] font-black uppercase tracking-widest text-black">AI Neural Render</span>
                    </div>
                </div>

                <div className="absolute top-4 right-4 flex flex-col gap-2">
                    <button onClick={handleShare} className="w-10 h-10 bg-white/90 backdrop-blur-md rounded-xl flex items-center justify-center text-black shadow-lg hover:bg-white transition-all border border-white/20"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"></path></svg></button>
                    <button onClick={handleDownload} className="w-10 h-10 bg-white/90 backdrop-blur-md rounded-xl flex items-center justify-center text-black shadow-lg hover:bg-white transition-all border border-white/20"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg></button>
                </div>
              </div>
              
              <div className="flex flex-col sm:flex-row gap-3 w-full max-w-sm pt-4">
                <Button className="flex-[2] py-4 shadow-xl shadow-black/10" onClick={() => window.open(product.imageUrl, '_blank')}>View Store</Button>
                <Button variant="secondary" className="flex-1 py-4" onClick={resetTryOn}>Retry</Button>
              </div>
            </div>
          ) : (
            <div className="space-y-8 flex-1">
              <div className="space-y-2 text-center md:text-left">
                <h2 className="text-3xl font-black tracking-tight">Virtual Fitting</h2>
                <p className="text-zinc-500 font-medium">Use your photo to visualize the drape and fit.</p>
              </div>

              <div className="space-y-6">
                <div 
                  onClick={() => fileInputRef.current?.click()}
                  className={`relative cursor-pointer border-2 border-dashed rounded-[2rem] p-8 flex flex-col items-center justify-center transition-all group ${image ? 'border-zinc-200 bg-zinc-50' : 'border-zinc-300 hover:border-black bg-white hover:bg-zinc-50/50'}`}
                >
                  <input type="file" accept="image/*" className="hidden" ref={fileInputRef} onChange={handleFileChange} />
                  {image ? (
                    <div className="relative w-40 aspect-[3/4] rounded-2xl overflow-hidden shadow-2xl">
                      <img src={image} className="w-full h-full object-cover" alt="User" />
                      <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                        <span className="text-white text-[10px] font-black uppercase tracking-widest">Change</span>
                      </div>
                    </div>
                  ) : (
                    <>
                      <div className="w-16 h-16 bg-zinc-100 rounded-2xl flex items-center justify-center mb-4 shadow-sm border border-zinc-200">
                        <svg className="w-8 h-8 text-black" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                      </div>
                      <p className="text-black font-bold">Upload Portrait</p>
                    </>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest ml-1">Height (cm)</label>
                    <input type="number" value={height} onChange={(e) => setHeight(e.target.value)} className="w-full px-5 py-4 bg-zinc-50 border border-zinc-200 rounded-2xl focus:ring-4 focus:ring-black/5 outline-none transition-all font-bold"/>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest ml-1">Weight (kg)</label>
                    <input type="number" value={weight} onChange={(e) => setWeight(e.target.value)} className="w-full px-5 py-4 bg-zinc-50 border border-zinc-200 rounded-2xl focus:ring-4 focus:ring-black/5 outline-none transition-all font-bold"/>
                  </div>
                </div>

                {user && (
                  <div className="flex items-center gap-3 px-4 py-3 bg-zinc-50 rounded-2xl border border-zinc-100 cursor-pointer select-none" onClick={() => setSaveBodyModel(!saveBodyModel)}>
                    <div className={`w-5 h-5 rounded-md border flex items-center justify-center transition-colors ${saveBodyModel ? 'bg-black border-black' : 'bg-white border-zinc-300'}`}>
                      {saveBodyModel && <svg className="w-3.5 h-3.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7"></path></svg>}
                    </div>
                    <span className="text-xs font-bold text-zinc-600">Update my Digital Body Model</span>
                  </div>
                )}

                <div className="pt-4">
                  <Button className="w-full py-5 text-sm uppercase tracking-[0.2em] font-black shadow-xl shadow-black/10" disabled={!image} onClick={handleGenerate}>Preview Look</Button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default TryOnModal;
